# Generated by Django 6.0.4 on 2026-04-23 00:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='color',
            field=models.CharField(default='#7c3aed', max_length=20),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('trial', 'Prueba gratuita'), ('active', 'Activa'), ('unpaid', 'Impaga'), ('expired', 'Vencida')], default='trial', max_length=20)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('mp_preference_id', models.CharField(blank=True, max_length=255)),
                ('mp_payment_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='tenants.tenant')),
            ],
        ),
    ]
