"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cvgs9lvjxo_3%u3_0ld0fixq1eay&&p*2b-ma+yxe+e$7*k@jk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'accounts',
    'tenants',
    'bookings',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.app_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# MercadoPago — reemplazá con tus credenciales reales
MP_ACCESS_TOKEN = 'TEST-0000000000000000-000000-00000000000000000000000000000000-000000000'
MP_USE_SANDBOX = True

# ─────────────────────────────────────────────────────────────
# CONFIGURACIÓN DE LA APP  ← EDITÁ ESTO ANTES DE CADA CLIENTE
# ─────────────────────────────────────────────────────────────
APP_CONFIG = {
    # Nombre de la app y tagline
    'name': 'ReservaPro',
    'tagline': 'Software de gestión de turnos y reservas',
    'description': 'Administrá tus turnos, clientes y agenda desde cualquier dispositivo. Sin papeles, sin confusiones.',

    # Tipo de negocio (para la landing page)
    'business_type': 'negocio',          # ej: "salón", "clínica", "taller"
    'business_types_list': [             # aparecen en la landing
        'salones de belleza',
        'clínicas y consultorios',
        'talleres mecánicos',
        'peluquerías',
        'centros de estética',
    ],

    # Etiquetas dentro del sistema
    'booking_label': 'Turno',            # o "Reserva", "Cita", etc.
    'client_label': 'Cliente',           # o "Paciente", "Vehículo", etc.
    'service_label': 'Servicio',         # o "Tratamiento", "Trabajo", etc.

    # Servicios del demo (los que se cargan al hacer clic en "Probar demo")
    'demo_services': [
        'Corte de cabello',
        'Tinte completo',
        'Manicura',
        'Pedicura',
        'Brushing',
        'Tratamiento capilar',
        'Mechas',
        'Depilación',
    ],

    # Color principal (hex)
    'color': '#7c3aed',

    # Icono/emoji de la app
    'icon': '📅',

    # Precios de membresía (ARS)
    'price_monthly': 5000,
    'price_yearly': 50000,

    # Contacto y redes (para el footer)
    'contact_email': 'hola@reservapro.com',
    'instagram': '',
    'whatsapp': '',

    # País / moneda
    'currency': 'ARS',
    'country': 'Argentina',
}
