"""add push_subscriptions and day_reminder_sent

Revision ID: 2f77f7a04275
Revises: c595d869ee44
Create Date: 2026-04-21 23:13:44.810647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f77f7a04275'
down_revision = 'c595d869ee44'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()

    # Check if push_subscriptions table already exists
    result = conn.execute(sa.text(
        "SELECT table_name FROM information_schema.tables "
        "WHERE table_schema = 'public' AND table_name = 'push_subscriptions'"
    ))
    if not result.fetchone():
        op.create_table('push_subscriptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('endpoint', sa.Text(), nullable=False),
        sa.Column('p256dh', sa.Text(), nullable=False),
        sa.Column('auth', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['staff_users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('endpoint')
        )

    # Check if day_reminder_sent column already exists
    result = conn.execute(sa.text(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_name = 'appointments' AND column_name = 'day_reminder_sent'"
    ))
    if not result.fetchone():
        with op.batch_alter_table('appointments', schema=None) as batch_op:
            batch_op.add_column(sa.Column('day_reminder_sent', sa.Boolean(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('day_reminder_sent')

    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
