"""add smtp fields to tenant

Revision ID: 5694b930af12
Revises: 5e8b829dc535
Create Date: 2026-04-25 18:16:18.193674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5694b930af12'
down_revision = '5e8b829dc535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_host', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('email_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('email_user', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('email_password', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('email_from', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('email_from')
        batch_op.drop_column('email_password')
        batch_op.drop_column('email_user')
        batch_op.drop_column('email_port')
        batch_op.drop_column('email_host')

    # ### end Alembic commands ###
