"""add client_email to appointments

Revision ID: 5e8b829dc535
Revises: 2f77f7a04275
Create Date: 2026-04-25 17:45:18.773022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8b829dc535'
down_revision = '2f77f7a04275'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_name = 'appointments' AND column_name = 'client_email'"
    ))
    if not result.fetchone():
        with op.batch_alter_table('appointments', schema=None) as batch_op:
            batch_op.add_column(sa.Column('client_email', sa.String(length=120), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('client_email')

    # ### end Alembic commands ###
