"""add membership fields to tenant

Revision ID: c595d869ee44
Revises: 
Create Date: 2026-04-21 22:59:22.569703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c595d869ee44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    # Check which columns already exist to make migration idempotent
    result = conn.execute(sa.text(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_name = 'tenants'"
    ))
    existing_columns = {row[0] for row in result}

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        if 'membership_status' not in existing_columns:
            batch_op.add_column(sa.Column('membership_status', sa.String(length=20), nullable=True))
        if 'membership_expires_at' not in existing_columns:
            batch_op.add_column(sa.Column('membership_expires_at', sa.DateTime(), nullable=True))
        if 'mp_payment_link' not in existing_columns:
            batch_op.add_column(sa.Column('mp_payment_link', sa.String(length=500), nullable=True))
        batch_op.alter_column('business_type',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=80),
               existing_nullable=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('business_type',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
        batch_op.drop_column('mp_payment_link')
        batch_op.drop_column('membership_expires_at')
        batch_op.drop_column('membership_status')

    # ### end Alembic commands ###
